name:  Regression Suite Run

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  regression-api-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"